import "@fontsource/mulish";
import Providers from "./providers/userProvider";
import "/globals.scss";

export const metadata = {
  title: "Car2Go",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
